config/routes.rb
Rails.application.routes.draw do
  resources :pages
  resources :movies

  root 'pages#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, length: {minimum: 1, maximum: 150},
                    presence: true
  validates :length, inclusion: 0..500,
                    presence: true
  validates :year, inclusion: 1800..2100,
                    presence: true
  validates :rating, inclusion: 1..5,
                    presence: true
  validates :format, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.order(sort_column + " " + sort_direction)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
#     @movie.length = (@movie.length / 60).to_s + " hr " + (@movie.length % 60).to_s + " min"
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :format, :length, :year, :rating)
    end

  def sort_column
    #     Sanitize
    Movie.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    #     Sanitize
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params[:page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
#     css_class = column == sort_column ? "current #{sort_direction}" : nil
#     direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
#     link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<!-- <%= form_for @movie, :html => { :class => "form-horizontal movie" } do |f| %>

    <% if @movie.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :format, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :format, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:format]) %>
  </div>
  <div class="control-group">
    <%= f.label :length, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :length, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:length]) %>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:year]) %>
  </div>
  <div class="control-group">
    <%= f.label :rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rating, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:rating]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            movies_path, :class => 'btn btn-default' %>

<% end %>
 -->

<div class="container">
  <%= form_for(@movie) do |f| %>
    <% if @movie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

        <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <select name="movie[format]" id="movie_format" class="form-control">
        <option value="DVD">DVD</option>
        <option value="VHS">VHS</option>
        <option value="STREAMING">Streaming</option>
      </select>
<!--       <%= f.label :format %><br>
      <%= f.text_field :format %> -->
    </div>
  <div class="control-group">
    <%= f.label :length, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :length, :class => 'form-control' %>
    </div>
    <%= error_span(@movie[:length]) %>
  </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.number_field :year %>
    </div>
    <div class="field">
      <div class="radio">
        <label><input type="radio" name="movie[rating]" value="01">1</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="movie[rating]" value="02">2</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="movie[rating]" value="03">3</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="movie[rating]" value="04">4</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="movie[rating]" value="05">5</label>
      </div>
<!--       <%= f.label :rating %><br>
      <%= f.number_field :rating %> -->
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/index.html.erb
<%- model_class = Movie -%>
<div class="jumbotron">
  <div class="container">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
  </div>
</div>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/movies">Movies</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "id"%></th>
      <th><%= sortable "title"%></th>
      <th><%= sortable "format"%></th>
      <th><%= sortable "length"%></th>
      <th><%= sortable "year"%></th>
      <th><%= sortable "rating"%></th>
      <th><%= sortable "created_at"%></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.id, movie_path(movie) %></td>
        <td><%= movie.title %></td>
        <td><%= movie.format %></td>
        <td><%= (movie.length / 60).to_s + " hr " + (movie.length % 60).to_s + " min" %></td>
        <td><%= movie.year %></td>
        <td><%= movie.rating %></td>
        <td><%=l movie.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_movie_path(movie), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      movie_path(movie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_movie_path,
            :class => 'btn btn-primary' %>

app/views/movies/new.html.erb
<%- model_class = Movie -%>

<div class="jumbotron">
  <div class="container">
    <div class="page-header">
      <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
    </div>
  </div>
</div>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/movies">Movies</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<%- model_class = Movie -%>
<div class="jumbotron">
  <div class="container">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    </div>
  </div>
</div>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/movies">Movies</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @movie.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:format) %>:</strong></dt>
  <dd><%= @movie.format %></dd>
  <dt><strong><%= model_class.human_attribute_name(:length) %>:</strong></dt>
  <dd><%= (@movie.length / 60).to_s + " hr " + (@movie.length % 60).to_s + " min" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @movie.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @movie.rating %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              movies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_movie_path(@movie), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/movies">Movies</a>
            </div>
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <h1>Matt's Movie Manager</h1>
                <p>Welcome to Matt's Movie Manager!  This site is a place where you can add in movies you have seen beforee and rate them.  Pretty simple, but it's kinda fun!</p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>